service: city-service
frameworkVersion: '3'

#todo add stage dev, prod, staging
params:
  default:
    region: eu-central-1
    profile: personal

provider:
  name: aws
  runtime: python3.9
  profile: ${param:profile}
  region: ${param:region}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
              - "secretsmanager:GetSecretValue"
          Resource: "*"
  httpApi:
    cors: true
functions:
  getCity:
    handler: src/interfaces/get_city.handler
    events:
      - httpApi:
          path: /
          method: get
  getDistance:
    handler: src/interfaces/get_distance.handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements


custom:
  pythonRequirements:
    usePoetry: true
    zip: true
